baseURL = '/'
languageCode = 'en'
title = 'Hugo Cat'
PygmentsCodeFences = true
PygmentsStyle = "solarized-dark256"
pluralizelisttitles = "false"
paginate  = 15
disableHugoGeneratorInject = false
enableEmoji = true

[params]
ava = "/img/cat.png"
owner ="Red Kitty"
talk = "Hello guys &#128075; im cool kitty..."
blogSection = ["blog"]
description = "Cat"
favicon = "/img/logo.svg"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 2

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 3

[[menu.main]]
name = "About"
url = "/about/"
weight = 4



[module]
  [module.hugoVersion]
    extended = true
    min = "0.111.3"
  
